# Generated by Django 5.2.6 on 2025-11-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
