# Generated by Django 5.2.7 on 2025-10-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_approved_on_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved_on',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
