# Generated by Django 5.2.6 on 2025-11-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reported',
            new_name='is_reported',
        ),
        migrations.AddField(
            model_name='product',
            name='report_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
