# Generated by Django 4.2.11 on 2025-11-03 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_reported_product_is_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerapplication',
            name='submitted_atagain',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
