# Generated by Django 4.2.11 on 2025-11-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sellerapplication_submitted_atagain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerapplication',
            name='submitted_atagain',
        ),
    ]
